---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: facebooc-deploy
  namespace: facebooc
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/sasachde/facebooc-deploy

